apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-uhhcugjb
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-uhhcugjb:e1dbece1bfe739d6c3aa3f5d5ca471e47c36ac21@sha256:f7f06a8ffc089f320c14b08d63f8a9c0fac591314088b58e6fd0965bd33e19c6
        name: container-image  
